cd ~/Desktop
mkdir bobmarley
cd bobmarley
mkdir cedella-marley
mkdir david-marley
mkdir ky-mani-marley
cd cedella-marley
mkdir skip-marley
cd ..
cd david-marley
touch daughter_1.child
touch daughter_2.child
mkdir zm-songs
cd zm-songs
touch drive.reggae
touch a_lifetime.reggae
cd ../..
cd ky-mani-marley
mkdir km-songs
mkdir movies
cd km-songs
touch dear_dad.reggae
touch mama.reggae
cd ..
cd movies
touch one_love.drama
touch shottaz.action
cd ../..
cd cedella-marley
cd skip-marley
mkdir sm_songs
cd sm_songs
touch lifeboat.reggae
touch lions.reggae
cd ~/Desktop